- id:                   usd
  symbol:               '$'
  type:                 fiat
  precision:            2
  base_factor:          1
  enabled:              true
  quick_withdraw_limit: 1000
  deposit_fee:          0
  withdraw_fee:         0

- id:                   btc
  symbol:               '฿'
  type:                 coin
  precision:            8
  base_factor:          100_000_000
  enabled:              true
  quick_withdraw_limit: 0.1
  deposit_fee:          0
  withdraw_fee:         0
  blockchain_key:       btc-testnet
  options:
    case_sensitive:                   true
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             true
    allow_multiple_deposit_addresses: false
    api_client: BTC
    json_rpc_endpoint:        http://admin:changeme@bitcoind:18332
    wallet_url_template:      https://testnet.blockchain.info/address/#{address}
    transaction_url_template: https://testnet.blockchain.info/tx/#{txid}

- id:                   eth
  symbol:               'Ξ'
  type:                 coin
  precision:            8
  base_factor:          1_000_000_000_000_000_000
  enabled:              true
  quick_withdraw_limit: 2
  deposit_fee:          0
  withdraw_fee:         0
  blockchain_key:       eth-rinkeby
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ETH
    json_rpc_endpoint:        http://geth:8545
    wallet_url_template:      https://rinkeby.etherscan.io/address/#{address}
    transaction_url_template: https://rinkeby.etherscan.io/tx/#{txid}

- id:                   trst
  symbol:               'Ξ'
  type:                 coin
  precision:            8
  base_factor:          1_000_000
  enabled:              true
  quick_withdraw_limit: 3000
  blockchain_key:       eth-rinkeby
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ERC20
    json_rpc_endpoint:        http://geth:8545
    erc20_contract_address:   '0x87099adD3bCC0821B5b151307c147215F839a110'
    wallet_url_template:      https://rinkeby.etherscan.io/address/#{address}
    transaction_url_template: https://rinkeby.etherscan.io/tx/#{txid}

